/*
Copyright 2021  Simon Arlott

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

@Library("uuid")
import uk.uuid.jenkins.pipeline.Cron
import uk.uuid.jenkins.pipeline.Email

def application_agent_labels() {
	def labels = ["Linux", "Python"]

	labels.add([
		linux: "GCC",
		windows: "GCC-mingw-w64",
	][PLATFORM])

	return labels.join(" && ")
}

def meson_opts() {
	return [
		linux: "",
		windows: "--cross cross64.ini",
	][PLATFORM]
}

pipeline {
	agent none
	triggers {
		cron("${Cron.schedule(this)}")
	}
	environment {
		PIPENV_VENV_IN_PROJECT = "1"
		PIPENV_SKIP_LOCK = "1"
	}
	stages {
		stage("Application") {
			matrix {
				axes {
					axis {
						name "PLATFORM"
						values "linux", "windows"
					}
				}
				agent {
					label application_agent_labels()
				}
				environment {
					TMPDIR = "${WORKSPACE_TMP}"
					DESTDIR= "${WORKSPACE_TMP}/DESTDIR"
				}
				stages {
					stage("Checkout") {
						steps {
							sh "git clean -fdx"
						}
					}
					stage("Prepare") {
						steps {
							sh "pipenv install meson ninja"
						}
					}
					stage("Build") {
						steps {
							dir(PLATFORM) {
								sh "pipenv run meson --buildtype=release build/ -Db_lto=true --unity on --unity-size 10000 ${meson_opts()}"
								sh "pipenv run ninja -C build/ -j 1"
							}
						}
						post {
							failure {
								sh "cat ${PLATFORM}/build/meson-logs/meson-log.txt"
							}
						}
					}
					stage("Install") {
						steps {
							dir(PLATFORM) {
								sh "pipenv run ninja -C build/ -j 1 install"
							}
						}
					}
				}
				post {
					cleanup {
						cleanWs()
					}
				}
			}
		}
	}
	post {
		always {
			script {
				Email.send(this)
			}
		}
	}
}
